// One-shot generator. Reads reference/openh264_data_tables.cpp,
// extracts CAVLC lookup arrays, and emits src/H264Decoder/Cavlc/CavlcTables.cs.
// Not part of the H264Decoder solution. Run via: dotnet run --project tools/CavlcGen
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

string here = AppContext.BaseDirectory;
string repoRoot = Path.GetFullPath(Path.Combine(here, "..", "..", "..", "..", ".."));
string src = Path.Combine(repoRoot, "tools", "CavlcGen", "reference", "openh264_data_tables.cpp");
string cabacSrc = Path.Combine(repoRoot, "tools", "CavlcGen", "reference", "openh264_common_tables.cpp");
string dst = Path.Combine(repoRoot, "src", "H264Decoder", "Cavlc", "CavlcTables.cs");
string cabacDst = Path.Combine(repoRoot, "src", "H264Decoder", "Cabac", "CabacInitTable.cs");
if (!File.Exists(src))
{
    Console.Error.WriteLine($"Reference file not found: {src}");
    return 1;
}
string text = File.ReadAllText(src);
string cabacText = File.Exists(cabacSrc) ? File.ReadAllText(cabacSrc) : "";

string[] wanted =
[
    "g_kuiVlcChromaTable",
    "g_kuiVlcTable_0", "g_kuiVlcTable_0_0", "g_kuiVlcTable_0_1", "g_kuiVlcTable_0_2", "g_kuiVlcTable_0_3",
    "g_kuiVlcTable_1", "g_kuiVlcTable_1_0", "g_kuiVlcTable_1_1", "g_kuiVlcTable_1_2", "g_kuiVlcTable_1_3",
    "g_kuiVlcTable_2", "g_kuiVlcTable_2_0", "g_kuiVlcTable_2_1", "g_kuiVlcTable_2_2", "g_kuiVlcTable_2_3",
    "g_kuiVlcTable_2_4", "g_kuiVlcTable_2_5", "g_kuiVlcTable_2_6", "g_kuiVlcTable_2_7",
    "g_kuiVlcTable_3",
    "g_kuiVlcTableNeedMoreBitsThread",
    "g_kuiVlcTableMoreBitsCount0", "g_kuiVlcTableMoreBitsCount1", "g_kuiVlcTableMoreBitsCount2",
    "g_kuiNcMapTable",
    "g_kuiVlcTrailingOneTotalCoeffTable",
    "g_kuiTotalZerosTable0", "g_kuiTotalZerosTable1", "g_kuiTotalZerosTable2", "g_kuiTotalZerosTable3",
    "g_kuiTotalZerosTable4", "g_kuiTotalZerosTable5", "g_kuiTotalZerosTable6", "g_kuiTotalZerosTable7",
    "g_kuiTotalZerosTable8", "g_kuiTotalZerosTable9", "g_kuiTotalZerosTable10",
    "g_kuiTotalZerosTable11", "g_kuiTotalZerosTable12", "g_kuiTotalZerosTable13", "g_kuiTotalZerosTable14",
    "g_kuiZeroLeftTable0", "g_kuiZeroLeftTable1", "g_kuiZeroLeftTable2", "g_kuiZeroLeftTable3",
    "g_kuiZeroLeftTable4", "g_kuiZeroLeftTable5", "g_kuiZeroLeftTable6",
    "g_kuiTotalZerosChromaTable0", "g_kuiTotalZerosChromaTable1", "g_kuiTotalZerosChromaTable2",
    "g_kuiTotalZerosBitNumMap",
    "g_kuiTotalZerosBitNumChromaMap",
    "g_kuiZeroLeftBitNumMap",
];

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("// CAVLC lookup tables ported from Cisco OpenH264");
sb.AppendLine("// (https://github.com/cisco/openh264), file");
sb.AppendLine("// codec/decoder/core/src/decoder_data_tables.cpp.");
sb.AppendLine("//");
sb.AppendLine("// Copyright (c) 2013, Cisco Systems. All rights reserved.");
sb.AppendLine("// Redistribution and use in source and binary forms, with or without");
sb.AppendLine("// modification, are permitted provided that the following conditions are met:");
sb.AppendLine("//   * Redistributions of source code must retain the above copyright notice,");
sb.AppendLine("//     this list of conditions and the following disclaimer.");
sb.AppendLine("//   * Redistributions in binary form must reproduce the above copyright notice,");
sb.AppendLine("//     this list of conditions and the following disclaimer in the documentation");
sb.AppendLine("//     and/or other materials provided with the distribution.");
sb.AppendLine("// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"");
sb.AppendLine("// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE");
sb.AppendLine("// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE");
sb.AppendLine("// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE");
sb.AppendLine("// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL");
sb.AppendLine("// DAMAGES.");
sb.AppendLine("// Re-generate with: dotnet run --project tools/CavlcGen");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace H264Decoder.Cavlc;");
sb.AppendLine();
sb.AppendLine("internal static class CavlcTables");
sb.AppendLine("{");

int emittedCount = 0;
foreach (string name in wanted)
{
    if (!TryEmit(text, name, sb))
    {
        Console.Error.WriteLine($"WARN: array '{name}' not found in source");
    }
    else
    {
        emittedCount++;
    }
}

sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(dst)!);
File.WriteAllText(dst, sb.ToString());
Console.WriteLine($"Wrote {dst} ({emittedCount}/{wanted.Length} arrays)");

// Also emit the CABAC init table (a 3D int8 array of (m, n) per [ctxIdx][model]).
if (cabacText.Length > 0)
{
    EmitCabacInit(cabacText, cabacDst);
}

return 0;

static void EmitCabacInit(string src, string dstPath)
{
    var rx = new Regex(@"const\s+int8_t\s+g_kiCabacGlobalContextIdx\s*\[[^\]]+\]\s*\[\s*4\s*\]\s*\[\s*2\s*\]\s*=\s*\{(.*?)\};",
        RegexOptions.Singleline);
    var m = rx.Match(src);
    if (!m.Success) { Console.Error.WriteLine("WARN: g_kiCabacGlobalContextIdx not found"); return; }

    string body = m.Groups[1].Value;
    body = Regex.Replace(body, @"//[^\n]*", string.Empty);
    body = Regex.Replace(body, @"/\*.*?\*/", string.Empty, RegexOptions.Singleline);
    body = body.Replace("CTX_NA", "-128");  // sentinel for "context not applicable"

    // Each context block: { {m,n}, {m,n}, {m,n}, {m,n} } (4 models)
    var blockRx = new Regex(@"\{\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}\s*,\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}\s*,\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}\s*,\s*\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}\s*\}");
    var entries = new List<(int[] m, int[] n)>();
    foreach (Match bm in blockRx.Matches(body))
    {
        int[] mm = new int[4];
        int[] nn = new int[4];
        for (int i = 0; i < 4; i++)
        {
            mm[i] = int.Parse(bm.Groups[1 + i * 2].Value, CultureInfo.InvariantCulture);
            nn[i] = int.Parse(bm.Groups[2 + i * 2].Value, CultureInfo.InvariantCulture);
        }
        entries.Add((mm, nn));
    }

    var sb2 = new StringBuilder();
    sb2.AppendLine("// <auto-generated>");
    sb2.AppendLine("// CABAC context init table ported from Cisco OpenH264 (BSD-2-Clause)");
    sb2.AppendLine("// common_tables.cpp / g_kiCabacGlobalContextIdx.");
    sb2.AppendLine("// Re-generate with: dotnet run --project tools/CavlcGen");
    sb2.AppendLine("// </auto-generated>");
    sb2.AppendLine();
    sb2.AppendLine("namespace H264Decoder.Cabac;");
    sb2.AppendLine();
    sb2.AppendLine("internal static class CabacInitTable");
    sb2.AppendLine("{");
    sb2.AppendLine("    public const int ContextCount = " + entries.Count + ";");
    sb2.AppendLine("    public const sbyte CtxNA = -128;");
    sb2.AppendLine();
    sb2.AppendLine($"    /// <summary>m,n for each (ctxIdx, model). Model 0 = I-slice; models 1..3 = P-slice with cabac_init_idc 0..2.</summary>");
    sb2.AppendLine($"    public static readonly sbyte[,,] MN = new sbyte[{entries.Count}, 4, 2]");
    sb2.AppendLine("    {");
    for (int i = 0; i < entries.Count; i++)
    {
        var (mm, nn) = entries[i];
        sb2.Append("        { ");
        for (int j = 0; j < 4; j++)
        {
            sb2.Append("{ ").Append(mm[j]).Append(", ").Append(nn[j]).Append(" }");
            if (j < 3) sb2.Append(", ");
        }
        sb2.AppendLine(i + 1 < entries.Count ? " }," : " }");
    }
    sb2.AppendLine("    };");
    sb2.AppendLine("}");

    Directory.CreateDirectory(Path.GetDirectoryName(dstPath)!);
    File.WriteAllText(dstPath, sb2.ToString());
    Console.WriteLine($"Wrote {dstPath} ({entries.Count} CABAC contexts)");
}

static bool TryEmit(string text, string name, StringBuilder sb)
{
    // Match: const uint8_t NAME[X] = { ... };  OR  const uint8_t NAME[X][2] = { ... };
    // Use a tolerant regex that captures everything between `= {` and `};`.
    var rx = new Regex(@"const\s+uint8_t\s+" + Regex.Escape(name)
                       + @"\s*(\[[^\]]+\])(\[\s*2\s*\])?\s*=\s*\{(.*?)\};",
                       RegexOptions.Singleline);
    var m = rx.Match(text);
    if (!m.Success) return false;

    bool is2D = m.Groups[2].Success;
    string body = m.Groups[3].Value;
    // Strip C/C++ comments (// to EOL, /* */).
    body = Regex.Replace(body, @"//[^\n]*", string.Empty);
    body = Regex.Replace(body, @"/\*.*?\*/", string.Empty, RegexOptions.Singleline);

    List<int> flat;
    if (is2D)
    {
        // Each element looks like { v, l }. Collect pairs.
        var pairRx = new Regex(@"\{\s*([0-9]+)\s*,\s*([0-9]+)\s*\}");
        flat = new List<int>();
        foreach (Match pm in pairRx.Matches(body))
        {
            flat.Add(int.Parse(pm.Groups[1].Value, CultureInfo.InvariantCulture));
            flat.Add(int.Parse(pm.Groups[2].Value, CultureInfo.InvariantCulture));
        }
    }
    else
    {
        // Comma-separated ints.
        flat = body.Split(',', StringSplitOptions.TrimEntries | StringSplitOptions.RemoveEmptyEntries)
                   .Where(s => s.Length > 0 && (char.IsDigit(s[0]) || s[0] == '-'))
                   .Select(s => int.Parse(s, CultureInfo.InvariantCulture))
                   .ToList();
    }

    string cs = ToCamel(name);
    sb.Append("    public static readonly byte[] ").Append(cs).Append(" = new byte[] { ");
    for (int i = 0; i < flat.Count; i++)
    {
        if (i > 0) sb.Append(", ");
        if (i % 32 == 0 && i > 0) { sb.AppendLine(); sb.Append("        "); }
        sb.Append(flat[i].ToString(CultureInfo.InvariantCulture));
    }
    sb.AppendLine(" };");
    return true;
}

static string ToCamel(string s)
{
    // g_kuiVlcTable_0 -> VlcTable0,  g_kuiTotalZerosTable10 -> TotalZerosTable10
    if (s.StartsWith("g_kui", StringComparison.Ordinal)) s = s[5..];
    return s;
}
